<?php
/**
 * @package     Joomla.Administrator
 * @subpackage  com_thm_organizer
 * @name        description managaer edit template
 * @author      Markus Bader markusDOTbaderATmniDOTthmDOTcom
 * @author      Daniel Kirsten danielDOTkirstenATmniDOTthmDOTde
 * @copyright   TH Mittelhessen 2011
 * @license     GNU GPL v.2
 * @link        www.mni.thm.de
 * @version     1.7.0
 */
defined("_JEXEC") or die;
?>

<script type="text/javascript">
	// make sure gpuntisid is unique
	function checkIfGpuntisIdIsUnique(selectedId) {	
		var gpuntisids =  // list of all gpuntisids generated by the responsible joomla model
		[''
			<?php		
				foreach($this->gpuntisids as $value) 
				{
					echo ", '".trim($value)."'";
				}
			?>
		];

		// check if id is in array
		result = gpuntisids.contains(selectedId);
		
		<?php
		// if on new view the entered gpuntisid must not exist
		// if on edit view it must exist
		if ($this->task == 'description.add') {
			echo 'return !result';
		} else {
			echo 'return result';
		}
		?>
	}
</script>

<form action="<?php echo JRoute::_('index.php?option=com_thm_organizer&view=description_edit&layout=edit&id='.(int) $this->item->id); ?>"
      method="post" name="adminForm" id="description_edit-form" class="form-validate">
	<fieldset class="adminform">
		<legend><?php echo JText::_( 'COM_THM_ORGANIZER_DS_DETAILS' ); ?></legend>
		<ul class="adminformlist">
<?php $emptyID = false; ?>
<?php foreach($this->form->getFieldset() as $field): ?>
			<li><?php
				echo $field->label;
				if ($field->fieldname == 'id' && $field->value == '') {
					$emptyID = true;
				}
				if ($field->fieldname == 'gpuntisID' && $emptyID == false) {
					$input = str_replace('type="text"', 'type="text" readonly="readonly"', $field->input);
					echo $input;
				} else {
					echo $field->input;
				}?></li>
<?php endforeach; ?>
		</ul>
	</fieldset>
	<div>
		<input type="hidden" name="task" value="description_edit.edit" />
		<?php echo JHtml::_('form.token'); ?>
	</div>
</form>