SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
SET foreign_key_checks = 0;

DROP TABLE IF EXISTS `#__thm_organizer_calendar`;
DROP TABLE IF EXISTS `#__thm_organizer_calendar_configuration_map`;
DROP TABLE IF EXISTS `#__thm_organizer_colors`;
DROP TABLE IF EXISTS `#__thm_organizer_degrees`;
DROP TABLE IF EXISTS `#__thm_organizer_departments`;
DROP TABLE IF EXISTS `#__thm_organizer_department_resources`;
DROP TABLE IF EXISTS `#__thm_organizer_fields`;
DROP TABLE IF EXISTS `#__thm_organizer_frequencies`;
DROP TABLE IF EXISTS `#__thm_organizer_grids`;
DROP TABLE IF EXISTS `#__thm_organizer_lessons`;
DROP TABLE IF EXISTS `#__thm_organizer_lesson_configurations`;
DROP TABLE IF EXISTS `#__thm_organizer_lesson_pools`;
DROP TABLE IF EXISTS `#__thm_organizer_lesson_subjects`;
DROP TABLE IF EXISTS `#__thm_organizer_lesson_teachers`;
DROP TABLE IF EXISTS `#__thm_organizer_mappings`;
DROP TABLE IF EXISTS `#__thm_organizer_methods`;
DROP TABLE IF EXISTS `#__thm_organizer_monitors`;
DROP TABLE IF EXISTS `#__thm_organizer_planning_periods`;
DROP TABLE IF EXISTS `#__thm_organizer_plan_pools`;
DROP TABLE IF EXISTS `#__thm_organizer_plan_programs`;
DROP TABLE IF EXISTS `#__thm_organizer_plan_subjects`;
DROP TABLE IF EXISTS `#__thm_organizer_pools`;
DROP TABLE IF EXISTS `#__thm_organizer_prerequisites`;
DROP TABLE IF EXISTS `#__thm_organizer_programs`;
DROP TABLE IF EXISTS `#__thm_organizer_rooms`;
DROP TABLE IF EXISTS `#__thm_organizer_room_features`;
DROP TABLE IF EXISTS `#__thm_organizer_room_features_map`;
DROP TABLE IF EXISTS `#__thm_organizer_room_types`;
DROP TABLE IF EXISTS `#__thm_organizer_schedules`;
DROP TABLE IF EXISTS `#__thm_organizer_subjects`;
DROP TABLE IF EXISTS `#__thm_organizer_subject_mappings`;
DROP TABLE IF EXISTS `#__thm_organizer_subject_teachers`;
DROP TABLE IF EXISTS `#__thm_organizer_teachers`;
DROP TABLE IF EXISTS `#__thm_organizer_user_lessons`;
DROP TABLE IF EXISTS `#__thm_organizer_user_schedules`;

SET foreign_key_checks = 1;
