SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
SET foreign_key_checks = 0;

DROP TABLE IF EXISTS `#__thm_organizer_blocks`;
DROP TABLE IF EXISTS `#__thm_organizer_buildings`;
DROP TABLE IF EXISTS `#__thm_organizer_calendar`;
DROP TABLE IF EXISTS `#__thm_organizer_calendar_configuration_map`;
DROP TABLE IF EXISTS `#__thm_organizer_campuses`;
DROP TABLE IF EXISTS `#__thm_organizer_categories`;
DROP TABLE IF EXISTS `#__thm_organizer_colors`;
DROP TABLE IF EXISTS `#__thm_organizer_course_participants`;
DROP TABLE IF EXISTS `#__thm_organizer_courses`;
DROP TABLE IF EXISTS `#__thm_organizer_degrees`;
DROP TABLE IF EXISTS `#__thm_organizer_department_resources`;
DROP TABLE IF EXISTS `#__thm_organizer_departments`;
DROP TABLE IF EXISTS `#__thm_organizer_event_coordinators`;
DROP TABLE IF EXISTS `#__thm_organizer_events`;
DROP TABLE IF EXISTS `#__thm_organizer_fields`;
DROP TABLE IF EXISTS `#__thm_organizer_frequencies`;
DROP TABLE IF EXISTS `#__thm_organizer_grids`;
DROP TABLE IF EXISTS `#__thm_organizer_group_publishing`;
DROP TABLE IF EXISTS `#__thm_organizer_groups`;
DROP TABLE IF EXISTS `#__thm_organizer_holidays`;
DROP TABLE IF EXISTS `#__thm_organizer_instance_participants`;
DROP TABLE IF EXISTS `#__thm_organizer_instance_groups`;
DROP TABLE IF EXISTS `#__thm_organizer_instance_persons`;
DROP TABLE IF EXISTS `#__thm_organizer_instance_rooms`;
DROP TABLE IF EXISTS `#__thm_organizer_instances`;
DROP TABLE IF EXISTS `#__thm_organizer_lesson_configurations`;
DROP TABLE IF EXISTS `#__thm_organizer_lesson_pools`;
DROP TABLE IF EXISTS `#__thm_organizer_lesson_subjects`;
DROP TABLE IF EXISTS `#__thm_organizer_lesson_teachers`;
DROP TABLE IF EXISTS `#__thm_organizer_mappings`;
DROP TABLE IF EXISTS `#__thm_organizer_methods`;
DROP TABLE IF EXISTS `#__thm_organizer_monitors`;
DROP TABLE IF EXISTS `#__thm_organizer_participants`;
DROP TABLE IF EXISTS `#__thm_organizer_persons`;
DROP TABLE IF EXISTS `#__thm_organizer_pools`;
DROP TABLE IF EXISTS `#__thm_organizer_prerequisites`;
DROP TABLE IF EXISTS `#__thm_organizer_programs`;
DROP TABLE IF EXISTS `#__thm_organizer_roles`;
DROP TABLE IF EXISTS `#__thm_organizer_rooms`;
DROP TABLE IF EXISTS `#__thm_organizer_roomtypes`;
DROP TABLE IF EXISTS `#__thm_organizer_runs`;
DROP TABLE IF EXISTS `#__thm_organizer_schedules`;
DROP TABLE IF EXISTS `#__thm_organizer_subject_events`;
DROP TABLE IF EXISTS `#__thm_organizer_subject_persons`;
DROP TABLE IF EXISTS `#__thm_organizer_subjects`;
DROP TABLE IF EXISTS `#__thm_organizer_terms`;
DROP TABLE IF EXISTS `#__thm_organizer_units`;
DROP TABLE IF EXISTS `#__thm_organizer_user_lessons`;

SET foreign_key_checks = 1;
